### ISSUE TITLE
Chicken Nugget Recipe Sauces

### ISSUE THREAD

**Issue by lsahn** [IntroToCode/Spring21_Recipes_Codemates8#10]
## 💬 Discussion topic

Chicken Nugget Recipe Sauces

## ❗ Potential issues

Should we add the sauces for the nuggets as well in the ingredients?

## 👥 People to consult

@ChaseThompson1992

**Comment by ChaseThompson1992** [comment]
Great idea and thanks for flagging this. I added some in the recipe area.
