### ISSUE TITLE
We should follow the grading rubric :)

### ISSUE THREAD

**Issue by sean-mccoy-haas** [IntroToCode/Spring21_Recipes_Codemates8#7]
## 💬 Discussion topic

Check out the bottom of the page here: https://bcourses.berkeley.edu/courses/1501227/assignments/8205345

## ❗ Potential issues

We're not totally following the rubric (e.g. we need to use issues... like this one!)

## 👥 People to consult

@ChaseThompson1992  @ofeklavian  @lsahn 

## 📃 Details

Looks like we'll be good if we just make a couple changes here and there. I think basically the only thing we're missing is an "Issue." Feel free to debate and/or close this issue below.

**Comment by ChaseThompson1992** [comment]
Good catch - I'll take a look tomorrow morning and refine

**Comment by ChaseThompson1992** [comment]
Is there a way to go back and add issues after merging the pull requests or do we need to do our pull requests again?
