### ISSUE TITLE
We need to make sure that all ingredients are included for each recipe

### ISSUE THREAD

**Issue by ChaseThompson1992** [IntroToCode/Spring21_Recipes_Codemates8#8]
## 💬 Discussion topic

Can everyone double check each recipe to ensure that all ingredients are included with each recipe? I believe they are but we may want to double check

## ❗ Potential issues

Maybe missing some ingredients

## 👥 People to consult

@sean-mccoy-haas @ofeklavian @lsahn 

## 📃 Details

Text

**Comment by sean-mccoy-haas** [comment]
@ChaseThompson1992 I think we should be all set (I made a few edits)
