### ISSUE TITLE
Acceptance Criteria

### ISSUE THREAD

**Issue by ChaseThompson1992** [IntroToCode/Spring21_Recipes_Codemates8#9]
## 💬 Discussion topic

We need to figure out a specific acceptance criteria for our pull requests.

## ❗ Potential issues

How do we evaluate new pull requests?

## 👥 People to consult

@sean-mccoy-haas @ofeklavian @lsahn 

## 📃 Details

I recommend we agree to the commit if we tangibly believe that the addition would be relevant to the recipe for most people.

**Comment by sean-mccoy-haas** [comment]
This is what we did when we were doing this live, so that makes sense to me. Thanks for documenting that decision @ChaseThompson1992

**Comment by ofeklavian** [comment]
Looks great! Thanks
